<?php

namespace Svr\Core\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * Created seeds for table system.system_modules_actions
 */
class SystemModulesActionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('system.system_modules_actions')->truncate();

        DB::table('system.system_modules_actions')->insert([
            [
                "module_slug"        => "users",
                "right_action"       => "list",
                "right_name"         => "Список пользователей",
                "right_slug"         => "users_list",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "data",
                "right_name"         => "Данные пользователя",
                "right_slug"         => "users_data",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "roles_list",
                "right_name"         => "Список ролей пользователя",
                "right_slug"         => "users_roles_list",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "avatar_add",
                "right_name"         => "Обновление аватара",
                "right_slug"         => "users_avatar_add",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "avatar_delete",
                "right_name"         => "Удаление аватара",
                "right_slug"         => "users_avatar_delete",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "forgot_password",
                "right_name"         => "Восстановление пароля пользователя",
                "right_slug"         => "users_forgot_password",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "roles",
                "right_action"       => "list",
                "right_name"         => "Список  ролей",
                "right_slug"         => "roles_list",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "roles",
                "right_action"       => "data",
                "right_name"         => "Данные роли",
                "right_slug"         => "roles_data",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "roles",
                "right_action"       => "rights_list",
                "right_name"         => "Список всех прав",
                "right_slug"         => "roles_rights_list",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "auth",
                "right_action"       => "login",
                "right_name"         => "Авторизация",
                "right_slug"         => "auth_login",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "auth",
                "right_action"       => "logout",
                "right_name"         => "Выход",
                "right_slug"         => "auth_logout",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "auth",
                "right_action"       => "info",
                "right_name"         => "Информация о себе",
                "right_slug"         => "auth_info",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "auth",
                "right_action"       => "set",
                "right_name"         => "Установка хозяйства",
                "right_slug"         => "auth_set",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "auth",
                "right_action"       => "herriot_requisites",
                "right_name"         => "Редактирование реквизитов хорриота",
                "right_slug"         => "auth_herriot_requisites",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "companies",
                "right_action"       => "data",
                "right_name"         => "Данные хозяйства",
                "right_slug"         => "companies_data",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "companies",
                "right_action"       => "list",
                "right_name"         => "Список хозяйств",
                "right_slug"         => "companies_list",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "companies",
                "right_action"       => "locations_list",
                "right_name"         => "Список хозяйств",
                "right_slug"         => "companies_locations_list",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "companies",
                "right_action"       => "company_objects_list",
                "right_name"         => "Список поднадзорных объектов",
                "right_slug"         => "companies_company_objects_list",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "directories",
                "right_action"       => "species",
                "right_name"         => "Справочник видов животных",
                "right_slug"         => "directories_species",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "directories",
                "right_action"       => "breeds",
                "right_name"         => "Справочник пород животных",
                "right_slug"         => "directories_breeds",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "directories",
                "right_action"       => "countries",
                "right_name"         => "Справочник стран",
                "right_slug"         => "directories_countries",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "directories",
                "right_action"       => "regions",
                "right_name"         => "Справочник регионов",
                "right_slug"         => "directories_regions",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "directories",
                "right_action"       => "districts",
                "right_name"         => "Справочник районов",
                "right_slug"         => "directories_districts",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "directories",
                "right_action"       => "keeping_purposes",
                "right_name"         => "Справочник целей содержания",
                "right_slug"         => "directories_keeping_purposes",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "directories",
                "right_action"       => "keeping_types",
                "right_name"         => "Справочник типов содержания",
                "right_slug"         => "directories_keeping_types",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "directories",
                "right_action"       => "tools_locations",
                "right_name"         => "Справочник мест нанесения маркировки",
                "right_slug"         => "directories_tools_locations",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "directories",
                "right_action"       => "genders",
                "right_name"         => "Справочник полов",
                "right_slug"         => "directories_genders",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "directories",
                "right_action"       => "out_basises",
                "right_name"         => "Справочник оснований выбытия",
                "right_slug"         => "directories_out_basises",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "directories",
                "right_action"       => "out_types",
                "right_name"         => "Справочник расходов выбытия",
                "right_slug"         => "directories_out_types",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "directories",
                "right_action"       => "mark_statuses",
                "right_name"         => "Справочник статусов маркирования",
                "right_slug"         => "directories_mark_statuses",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "directories",
                "right_action"       => "mark_tool_types",
                "right_name"         => "Справочник типов средств маркирования",
                "right_slug"         => "directories_mark_tool_types",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "directories",
                "right_action"       => "mark_types",
                "right_name"         => "Справочник типов маркирования",
                "right_slug"         => "directories_mark_types",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "notifications",
                "right_action"       => "list",
                "right_name"         => "Список уведомлений пользователя",
                "right_slug"         => "notifications_list",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "notifications",
                "right_action"       => "data",
                "right_name"         => "Полная информация по уведомлению",
                "right_slug"         => "notifications_data",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "notifications",
                "right_action"       => "read_all",
                "right_name"         => "Прочтение всех уведомлений",
                "right_slug"         => "notifications_read_all",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "applications",
                "right_action"       => "list",
                "right_name"         => "Список заявок хозяйства",
                "right_slug"         => "applications_list",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "edit",
                "right_name"         => "Редактирование пользователя",
                "right_slug"         => "users_edit",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "password_change",
                "right_name"         => "Смена пароля",
                "right_slug"         => "users_password_change",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "delete",
                "right_name"         => "Удаление пользователя",
                "right_slug"         => "users_delete",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "status",
                "right_name"         => "Статус пользователя",
                "right_slug"         => "users_status",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "company_add",
                "right_name"         => "Установка компании пользователя",
                "right_slug"         => "users_company_add",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "role_add",
                "right_name"         => "Установка роли пользователя",
                "right_slug"         => "users_role_add",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "role_delete",
                "right_name"         => "Удаление роли пользователя",
                "right_slug"         => "users_role_delete",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "location_add",
                "right_name"         => "Установка области\района",
                "right_slug"         => "users_location_add",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "location_delete",
                "right_name"         => "Удаление области\района",
                "right_slug"         => "users_location_delete",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "herriot_req_add",
                "right_name"         => "Добавление реквизитов хорриота",
                "right_slug"         => "users_herriot_req_add",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "send_requisites",
                "right_name"         => "Отправка пользователю реквизитов входа",
                "right_slug"         => "users_send_requisites",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "roles",
                "right_action"       => "create",
                "right_name"         => "Добавление роли",
                "right_slug"         => "roles_create",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "roles",
                "right_action"       => "edit",
                "right_name"         => "Редактирование роли",
                "right_slug"         => "roles_edit",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "roles",
                "right_action"       => "delete",
                "right_name"         => "Удаление роли",
                "right_slug"         => "roles_delete",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "roles",
                "right_action"       => "status",
                "right_name"         => "Статус роли",
                "right_slug"         => "roles_status",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "roles",
                "right_action"       => "right_add",
                "right_name"         => "Добавление права роли",
                "right_slug"         => "roles_right_add",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "roles",
                "right_action"       => "right_delete",
                "right_name"         => "Удаление права роли",
                "right_slug"         => "roles_right_delete",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "auth",
                "right_action"       => "install",
                "right_name"         => "Переустановка системы",
                "right_slug"         => "auth_install",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "auth",
                "right_action"       => "migrate",
                "right_name"         => "Накатывание миграций",
                "right_slug"         => "auth_migrate",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "companies",
                "right_action"       => "create",
                "right_name"         => "Создать хозяйство",
                "right_slug"         => "companies_create",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "companies",
                "right_action"       => "status",
                "right_name"         => "Статус хозяйства",
                "right_slug"         => "companies_status",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "companies",
                "right_action"       => "edit",
                "right_name"         => "Редактирование хозяйства",
                "right_slug"         => "companies_edit",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "companies",
                "right_action"       => "location_add",
                "right_name"         => "Установка области\района",
                "right_slug"         => "companies_location_add",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "companies",
                "right_action"       => "location_delete",
                "right_name"         => "Удаление области\района",
                "right_slug"         => "companies_location_delete",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "applications",
                "right_action"       => "data",
                "right_name"         => "Полная информация по заявке",
                "right_slug"         => "applications_data",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "animals",
                "right_action"       => "list",
                "right_name"         => "Список животных",
                "right_slug"         => "animals_list",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "animals",
                "right_action"       => "data",
                "right_name"         => "Полная информация по животному",
                "right_slug"         => "animals_data",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "selex",
                "right_action"       => "login",
                "right_name"         => "Авторизация пользователя Селекс",
                "right_slug"         => "selex_login",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "selex",
                "right_action"       => "send_animals",
                "right_name"         => "Передача данных по животным",
                "right_slug"         => "selex_send_animals",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "selex",
                "right_action"       => "get_animals",
                "right_name"         => "Получение данных по животным",
                "right_slug"         => "selex_get_animals",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "selex",
                "right_action"       => "send_animals_z",
                "right_name"         => "Подтверждение получения данных по животным",
                "right_slug"         => "selex_send_animals_z",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "create",
                "right_name"         => "Создание пользователя",
                "right_slug"         => "users_create",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "users",
                "right_action"       => "company_delete",
                "right_name"         => "Удаление компании пользователя",
                "right_slug"         => "users_company_delete",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "companies",
                "right_action"       => "delete",
                "right_name"         => "Удаление хозяйства",
                "right_slug"         => "companies_delete",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "applications",
                "right_action"       => "animal_add",
                "right_name"         => "Добавление животного в заявку",
                "right_slug"         => "applications_animal_add",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "applications",
                "right_action"       => "status",
                "right_name"         => "Изменение статуса заявки",
                "right_slug"         => "applications_status",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "applications",
                "right_action"       => "animal_delete",
                "right_name"         => "Удаление животного из заявки",
                "right_slug"         => "applications_animal_delete",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "animals",
                "right_action"       => "mark_edit",
                "right_name"         => "Редактирование средства маркирования",
                "right_slug"         => "animals_mark_edit",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "animals",
                "right_action"       => "mark_photo_edit",
                "right_name"         => "Редактирование фотографии средства маркирования",
                "right_slug"         => "animals_mark_photo_edit",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "animals",
                "right_action"       => "mark_photo_delete",
                "right_name"         => "Удаление фотографии средства маркирования",
                "right_slug"         => "animals_mark_photo_delete",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "animals",
                "right_action"       => "animal_keeping_object_edit",
                "right_name"         => "Редактирование объекта содержания животного",
                "right_slug"         => "animals_animal_keeping_object_edit",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "animals",
                "right_action"       => "animal_birth_object_edit",
                "right_name"         => "Редактирование объекта рождения животного",
                "right_slug"         => "animals_animal_birth_object_edit",
                "right_content_type" => "json",
                "right_log_write"    => "enabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "auth",
                "right_action"       => "herriot_error_check",
                "right_name"         => "Запуск проверки неизвестных ошибок из хорриота",
                "right_slug"         => "auth_herriot_error_check",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "dashboards",
                "right_action"       => "average_registration_time_by_day",
                "right_name"         => "Среднее время регистрации по дням",
                "right_slug"         => "dashboards_average_registration_time_by_day",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "dashboards",
                "right_action"       => "animal_registration_count_by_day",
                "right_name"         => "Количество зарегистрированных животных по дням",
                "right_slug"         => "dashboards_animal_registration_count_by_day",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "dashboards",
                "right_action"       => "animal_add_count_by_day",
                "right_name"         => "Количество добавленных животных по дням",
                "right_slug"         => "dashboards_animal_add_count_by_day",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "auth",
                "right_action"       => "clean_company_animals",
                "right_name"         => "Очистка животных компании",
                "right_slug"         => "auth_clean_company_animals",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "animals",
                "right_action"       => "mark_edit_group",
                "right_name"         => "Групповое редактирование средства маркирования",
                "right_slug"         => "animals_mark_edit_group",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "animals",
                "right_action"       => "animal_object_edit_group",
                "right_name"         => "Групповое редактирование места рождения, содержания, типа и вида содержания",
                "right_slug"         => "animals_animal_object_edit_group",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "companies",
                "right_action"       => "set_company_objects_favorite",
                "right_name"         => "Установка поднадзорных объектов в избранное",
                "right_slug"         => "companies_set_company_objects_favorite",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "companies",
                "right_action"       => "unset_company_objects_favorite",
                "right_name"         => "Удаление поднадзорных объектов из избранного",
                "right_slug"         => "companies_unset_company_objects_favorite",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "animals",
                "right_action"       => "animal_keeping_purpose_edit",
                "right_name"         => "Редактирование целей содержания",
                "right_slug"         => "animals_animal_keeping_purpose_edit",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                "module_slug"        => "animals",
                "right_action"       => "animal_keeping_type_edit",
                "right_name"         => "Редактирование видов содержания",
                "right_slug"         => "animals_animal_keeping_type_edit",
                "right_content_type" => "json",
                "right_log_write"    => "disabled",
                "created_at"         => Carbon::now()->format('Y-m-d H:i:s'),
                "updated_at"         => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ]);

        DB::statement("SELECT setval('system.system_modules_actions_right_id_seq', (SELECT MAX(right_id) from system.system_modules_actions))");
    }
}
