<?php

namespace Svr\Core\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class table_data_system_modules_actions extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('system.system_modules_actions')->truncate();

        DB::table('system.system_modules_actions')->insert([
            [
                "module_slug" => "users",
                "right_action" => "list",
                "right_name" => "Список         пользователей",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "data",
                "right_name" => "Данные         пользователя",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "roles_list",
                "right_name" => "Список         ролей           пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "avatar_add",
                "right_name" => "Обновление     аватара",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "avatar_delete",
                "right_name" => "Удаление     аватара",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "forgot_password",
                "right_name" => "Восстановление пароля пользователя",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "roles",
                "right_action" => "list",
                "right_name" => "Список         ролей",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "roles",
                "right_action" => "data",
                "right_name" => "Данные         роли",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "roles",
                "right_action" => "rights_list",
                "right_name" => "Список         всех            прав",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "auth",
                "right_action" => "login",
                "right_name" => "Авторизация",
                "right_slug" => "public",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "auth",
                "right_action" => "logout",
                "right_name" => "Выход",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "auth",
                "right_action" => "info",
                "right_name" => "Информация     о               себе",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "auth",
                "right_action" => "set",
                "right_name" => "Установка      хозяйства",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "auth",
                "right_action" => "herriot_requisites",
                "right_name" => "Редактирование реквизитов хорриота",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "companies",
                "right_action" => "data",
                "right_name" => "Данные         хозяйства",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "companies",
                "right_action" => "list",
                "right_name" => "Список         хозяйств",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "companies",
                "right_action" => "locations_list",
                "right_name" => "Список         хозяйств",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "companies",
                "right_action" => "company_objects_list",
                "right_name" => "Список поднадзорных объектов",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "directories",
                "right_action" => "species",
                "right_name" => "Справочник видов животных",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "directories",
                "right_action" => "breeds",
                "right_name" => "Справочник пород животных",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "directories",
                "right_action" => "countries",
                "right_name" => "Справочник стран",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "directories",
                "right_action" => "regions",
                "right_name" => "Справочник регионов",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "directories",
                "right_action" => "districts",
                "right_name" => "Справочник районов",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "directories",
                "right_action" => "keeping_purposes",
                "right_name" => "Справочник целей содержания",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "directories",
                "right_action" => "keeping_types",
                "right_name" => "Справочник типов содержания",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "directories",
                "right_action" => "tools_locations",
                "right_name" => "Справочник мест нанесения маркировки",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "directories",
                "right_action" => "genders",
                "right_name" => "Справочник полов",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "directories",
                "right_action" => "out_basises",
                "right_name" => "Справочник оснований выбытия",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "directories",
                "right_action" => "out_types",
                "right_name" => "Справочник расходов выбытия",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "directories",
                "right_action" => "mark_statuses",
                "right_name" => "Справочник статусов маркирования",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "directories",
                "right_action" => "mark_tool_types",
                "right_name" => "Справочник типов средств маркирования",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "directories",
                "right_action" => "mark_types",
                "right_name" => "Справочник типов маркирования",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "notifications",
                "right_action" => "list",
                "right_name" => "Список уведомлений пользователя",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "notifications",
                "right_action" => "data",
                "right_name" => "Полная информация по уведомлению",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "notifications",
                "right_action" => "read_all",
                "right_name" => "Прочтение всех уведомлений",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "applications",
                "right_action" => "list",
                "right_name" => "Список заявок хозяйства",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "edit",
                "right_name" => "Редактирование пользователя",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "password_change",
                "right_name" => "Смена пароля",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "delete",
                "right_name" => "Удаление       пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "status",
                "right_name" => "Статус         пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "company_add",
                "right_name" => "Установка      компании            пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "role_add",
                "right_name" => "Установка      роли            пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "role_delete",
                "right_name" => "Удаление       роли            пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "location_add",
                "right_name" => "Установка области\района",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "location_delete",
                "right_name" => "Удаление области\района",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "herriot_req_add",
                "right_name" => "Добавление реквизитов хорриота",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "send_requisites",
                "right_name" => "Отправка пользователю реквизитов входа",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "roles",
                "right_action" => "create",
                "right_name" => "Добавление     роли",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "roles",
                "right_action" => "edit",
                "right_name" => "Редактирование роли",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "roles",
                "right_action" => "delete",
                "right_name" => "Удаление       роли",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "roles",
                "right_action" => "status",
                "right_name" => "Статус         роли",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "roles",
                "right_action" => "right_add",
                "right_name" => "Добавление     права           роли",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "roles",
                "right_action" => "right_delete",
                "right_name" => "Удаление       права           роли",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "auth",
                "right_action" => "install",
                "right_name" => "Переустановка системы",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "auth",
                "right_action" => "migrate",
                "right_name" => "Накатывание миграций",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "companies",
                "right_action" => "create",
                "right_name" => "Создать        хозяйство",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "companies",
                "right_action" => "status",
                "right_name" => "Статус         хозяйства",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "companies",
                "right_action" => "edit",
                "right_name" => "Редактирование хозяйства",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "companies",
                "right_action" => "location_add",
                "right_name" => "Установка области\района",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "companies",
                "right_action" => "location_delete",
                "right_name" => "Удаление области\района",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "applications",
                "right_action" => "data",
                "right_name" => "Полная информация по заявке",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "animals",
                "right_action" => "list",
                "right_name" => "Список животных",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "animals",
                "right_action" => "data",
                "right_name" => "Полная информация по животному",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "selex",
                "right_action" => "login",
                "right_name" => "Авторизация пользователя Селекс",
                "right_slug" => "public",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "selex",
                "right_action" => "send_animals",
                "right_name" => "Передача данных по животным",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "selex",
                "right_action" => "get_animals",
                "right_name" => "Получение данных по животным",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "selex",
                "right_action" => "send_animals",
                "right_name" => "Подтверждение получения данных по животным",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "create",
                "right_name" => "Создание       пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "users",
                "right_action" => "company_delete",
                "right_name" => "Удаление       компании            пользователя",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "companies",
                "right_action" => "delete",
                "right_name" => "Удаление       хозяйства",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "applications",
                "right_action" => "animal_add",
                "right_name" => "Добавление животного в заявку",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "applications",
                "right_action" => "status",
                "right_name" => "Изменение статуса заявки",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "applications",
                "right_action" => "animal_delete",
                "right_name" => "Удаление животного из заявки",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "animals",
                "right_action" => "mark_edit",
                "right_name" => "Редактирование средства маркирования",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "animals",
                "right_action" => "mark_photo_edit",
                "right_name" => "Редактирование фотографии средства маркирования",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "animals",
                "right_action" => "mark_photo_delete",
                "right_name" => "Удаление фотографии средства маркирования",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "animals",
                "right_action" => "animal_keeping_object_edit",
                "right_name" => "Редактирование объекта содержания животного",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "animals",
                "right_action" => "animal_birth_object_edit",
                "right_name" => "Редактирование объекта рождения животного",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "enabled",
            ],
            [
                "module_slug" => "auth",
                "right_action" => "herriot_error_check",
                "right_name" => "Запуск проверки неизвестных ошибок из хорриота",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "dashboards",
                "right_action" => "average_registration_time_by_day",
                "right_name" => "Среднее время регистрации по дням",
                "right_slug" => "public",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "dashboards",
                "right_action" => "animal_registration_count_by_day",
                "right_name" => "Количество зарегистрированных животных по дням",
                "right_slug" => "public",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "dashboards",
                "right_action" => "animal_add_count_by_day",
                "right_name" => "Количество добавленных животных по дням",
                "right_slug" => "public",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "auth",
                "right_action" => "clean_company_animals",
                "right_name" => "Очистка животных компании",
                "right_slug" => "admin",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "animals",
                "right_action" => "mark_edit_group",
                "right_name" => "Групповое редактирование средства маркирования",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "animals",
                "right_action" => "animal_object_edit_group",
                "right_name" => "Групповое редактирование места рождения, содержания, типа и вида содержания",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "companies",
                "right_action" => "set_company_objects_favorite",
                "right_name" => "Установка поднадзорных объектов в избранное",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "companies",
                "right_action" => "unset_company_objects_favorite",
                "right_name" => "Удаление поднадзорных объектов из избранного",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "animals",
                "right_action" => "animal_keeping_purpose_edit",
                "right_name" => "Редактирование целей содержания",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
            [
                "module_slug" => "animals",
                "right_action" => "animal_keeping_type_edit",
                "right_name" => "Редактирование видов содержания",
                "right_slug" => "user",
                "right_content_type" => "json",
                "right_log_write" => "disabled",
            ],
        ]);
    }
}
